### ISSUE TITLE
uninitialized constant Lingo::Attendee::VectorFilter::DEFAULT_SRC_SEP (NameError)

### ISSUE THREAD

**Issue by svelsae** [lex-lingo/lingo#16]
I got an Error while running lingosrv from the ubuntu repositories (v1.10.0)

`/var/lib/gems/2.5.0/gems/lingo-1.10.0/lib/lingo/srv.rb:39:in` `<class:Srv>': uninitialized constant Lingo::Attendee::VectorFilter::DEFAULT_SRC_SEP (NameError)
Did you mean?  Lingo::Attendee::VectorFilter::DEFAULT_SRC_SEPARATOR `

The line in question is:
https://github.com/lex-lingo/lingo/blob/75a6d59ccb4cc86c923ec8b33241d49a7823fdef/lib/lingo/srv.rb#L39

...and the corresponding definition in VectorFilter is:
https://github.com/lex-lingo/lingo/blob/75a6d59ccb4cc86c923ec8b33241d49a7823fdef/lib/lingo/attendee/vector_filter.rb#L86

Looks like the constant was renamed in VectorFilter.

**Comment by blackwinter** [comment]
You're correct, the constant was renamed in 3f59438 (more than four years ago!) and the usage in `Lingo::Srv` wasn't updated. I'm sorry about that! I'll release a new version soon. For the time being, you can set `src` in your `vector_filter` config to `|` instead of `true` as a workaround. Thank you for reporting this!

**Comment by blackwinter** [comment]
I've released [version 1.10.1](https://rubygems.org/gems/lingo/versions/1.10.1).
